### ISSUE TITLE
[Bug] TypeError: Cannot read property 'append' of undefined

### ISSUE THREAD

**Issue by kapiljaveri** [gucong3000/postcss-html#17]
In v0.11.0, I get the following error when running a postcss gulp task which leverages postcss-html and postcss-import:

Message:
    Cannot read property 'append' of undefined
Details:
    fileName: C:\Users\kjaveri\Desktop\postcss-html-test\index.html
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
Stack:
TypeError: Cannot read property 'append' of undefined
    at Root.document.append (C:\Users\kjaveri\Desktop\postcss-html-test\node_modules\postcss-html\lib\parser.js:60:12)
    at stmt.nodes.forEach.node (C:\Users\kjaveri\Desktop\postcss-html-test\node_modules\postcss-import\index.js:122:16)
    at Array.forEach (<anonymous>)
    at bundle.forEach.stmt (C:\Users\kjaveri\Desktop\postcss-html-test\node_modules\postcss-import\index.js:120:18)
    at Array.forEach (<anonymous>)
    at applyStyles (C:\Users\kjaveri\Desktop\postcss-html-test\node_modules\postcss-import\index.js:112:10)
    at parseStyles.then.bundle (C:\Users\kjaveri\Desktop\postcss-html-test\node_modules\postcss-import\index.js:55:7)
    at <anonymous>

It complains about [this.last](https://github.com/gucong3000/postcss-html/commit/6f252374c8ff0d10dc8317b76b5515add1d2397f#diff-3fab227e34d65fe9bb2d6ea53eec41cfR60) being undefined hence causing the append to fail.

Attached is the sample code to help reproduce this issue. Run `npm intall` and then `npm test` which would invoke the gulp task.
[postcss-html-test.zip](https://github.com/gucong3000/postcss-html/files/1469099/postcss-html-test.zip)

Thanks!

**Comment by gucong3000** [comment]
Fixed in upstream [gulp-html-postcss@7.0.2](https://www.npmjs.com/package/gulp-html-postcss)

**Comment by gucong3000** [comment]
To resolve this problem, please use `gulp-html-postcss`

`gulpfile.js`:
```diff
@@ -1,14 +1,13 @@
 'use strict';
 const gulp = require('gulp');
-const postcss = require('gulp-postcss');
+const postcss = require('gulp-html-postcss');
 const postcssImport = require('postcss-import');
-const htmlSyntax = require('postcss-html');

 gulp.task('default', () => gulp.src('index.html')
   .pipe(postcss([
     postcssImport({
       path: ['./']
     })
-  ], { parser: htmlSyntax }))
+  ]))
   .pipe(gulp.dest('./build'))
 );
```
`package.json`:
```diff
@@ -11,9 +11,8 @@
   "devDependencies": {
     "gulp": "github:gulpjs/gulp#4.0",
     "gulp-cli": "^1.4.0",
-    "gulp-postcss": "^7.0.0",
+    "gulp-html-postcss": "^7.0.2",
     "postcss": "^6.0.14",
-    "postcss-html": "^0.10.0",
     "postcss-import": "^11.0.0"
   }
 }
```
[postcss-html-test.zip](https://github.com/gucong3000/postcss-html/files/1473827/postcss-html-test.zip)

**Comment by kapiljaveri** [comment]
Awesome, thank you!
