### ISSUE TITLE
Problem with inline styles and some stylelint rules

### ISSUE THREAD

**Issue by kaisermann** [gucong3000/postcss-html#70]
I understand that it can be very useful to also lint inline styles, but there are some `stylelint` rules that aren't much friendly with them. 

For example, `no-missing-end-of-source-newline`:
![image](https://user-images.githubusercontent.com/12702016/42905266-e6c2b04c-8aad-11e8-967b-fee1908783f0.png)

Is there a way to disable the inline style linting?

**Comment by gucong3000** [comment]
Not at the moment, but I will work on it.

**Comment by gucong3000** [comment]
```html
<a style="/* stylelint-disable */ color: red; /* stylelint-enable */"></a>
```
